---
# Slurm config (optional)
name: "SLURM"   # MUST BE "SLURM"

# Required
partition: "dev"
job-name: "Data Preparation"    # this will be the experiment's name in slurm

# Required - Cluster Specific
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 1
time: 200  # Runtime in Wallclock Time. Can be int or str in form "HH:MM:SS"

mem-per-cpu: 40000 # Optional - Cluster specific

# Optional Code Copy: Both Args are required.
experiment_copy_dst: /home/kit/anthropomatik/km8809/BA/BA_LTSF_w_Transformer2/      # optional. dir TO which the current code will be copied. Useful to prevent unintentional changes while the job is in queue.
experiment_copy_auto_dst: /home/kit/anthropomatik/km8809/BA/BA_LTSF_w_Transformer2/  # will autoincrement and create a dir TO which the current code will be copied. Useful to prevent unintentional changes while the job is in queue.
experiment_copy_src: /home/kit/anthropomatik/km8809/BA/BA_LTSF_w_Transformer2/      # optional. dir FROM which the current code will be copied. Useful to prevent unintentional changes while the job is in queue.


---
# DEFAULT parameters (Optional)
name: "DEFAULT"   # MUST BE 'DEFAULT'

# Implementation default parameters
# Will be overwritten by named experiments.
params:
  root_path: /home/kit/anthropomatik/km8809/BA/BA_LTSF_w_Transformer/data/UNI2
  save_path: /home/kit/anthropomatik/km8809/BA/BA_LTSF_w_Transformer/data/UNI2/univ2_pt_full.pkl

  file_paths: [ univ2_pt0, univ2_pt1, univ2_pt2, univ2_pt3, univ2_pt4, univ2_pt5, univ2_pt6, univ2_pt7, univ2_pt8 ]

---
# Experiment 1
name: "Data_Preparation"

# Required: Can also be set in DEFAULT
path: /home/kit/anthropomatik/km8809/BA/BA_LTSF_w_Transformer/results   # location to save results in
repetitions: 1    # number of times one set of parameters is run